version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myriam4life
      POSTGRES_DB: lets-learn-nextjs
    networks:
      - mahmoud
networks:
  mahmoud:
